### PR TITLE
NEW: importing

### PR DESCRIPTION
**Pull request by ebolyen**
[qiime2_tools_import.xml.txt](https://github.com/qiime2/q2galaxy/files/6556068/qiime2_tools_import.xml.txt)

### CODE REVIEW

**Comment by ebolyen** [comment]
tests failed :(

**Comment by ebolyen** [comment]
That passed.
[tool_test_output.html.txt](https://github.com/qiime2/q2galaxy/files/6557133/tool_test_output.html.txt)

**Comment by ebolyen** [comment]
@gregcaporaso, @Oddant1, or @thermokarst, any interest in taking this for a spin? It should be ready to go.

**Comment by ebolyen** [comment]
Updated tool:
[qiime2_tools_import.xml.txt](https://github.com/qiime2/q2galaxy/files/6563473/qiime2_tools_import.xml.txt)

**Review by thermokarst — COMMENTED** [review]
This is awesome, @ebolyen! I haven not reviewed code, nor performed a particularly extensive hands-on test, but I have spent some time kicking the tires, and overall this seems great! I did manage to shoot myself in the foot once when importing EMP SE sequences - somehow I imported barcodes as seqs (and vice versa) which cause a world of hurt. I guess that doesn't normally happen with say q2cli, because q2cli doesn't do any file renaming.

One "wish list" item, would it be possible for the format dropdown to default to the semantic type's `artifact_format`? 
Screen Shot 2021-06-02 at 4 58 48 PM
It's not a show-stopper or anything, but I figured I would ask, in case it was a relatively easy tweak.

Thanks! 🦖

**Comment by ebolyen** [comment]
Good call @thermokarst! It was pretty easy to add, although I was definitely wishing there was just a utility already in the sdk.

**Pull request merged**
